### PR TITLE
Added italian language

### PR DESCRIPTION
**Pull request by paoloconi96**

### CODE REVIEW

**Comment by paoloconi96** [comment]
@DenisCarriere Could you please merge this? I would love to start using it.
Thank you a lot

**Comment by DenisCarriere** [comment]
@paoloconi96 will do! sorry the delay, thank you for pinging me again as a reminder 😄

**Comment by DenisCarriere** [comment]
Published under `v1.1.5 `

**Comment by paoloconi96** [comment]
Thank you!

**Pull request merged**
